spring.application.name=library-managment
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/LENOVO/h2db/librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
